name: Run Discord Bot ON/OFF Cycle

on:
  schedule:
    - cron: '0 */4 * * *' # Lance toutes les 4 heures
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Create .env file
        run: |
          echo "DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}" > .env
          echo "DEEPSEEK_API_KEY=${{ secrets.DEEPSEEK_API_KEY }}" >> .env
          echo "DEEPSEEK_BASE_URL=${{ secrets.DEEPSEEK_BASE_URL }}" >> .env
          echo "DEEPSEEK_MODEL=${{ secrets.DEPPSEEK_MODEL }}" >> .env

      - name: Build Docker image
        run: docker build -t discord-bot:latest -f Dockerfile .

      - name: Start container with docker compose
        run: docker compose -f ./docker-compose.yml up -d

      - name: Keep job alive for 2 hours
        run: sleep 7200

      - name: Tear down container
        if: always()
        run: docker compose -f ./docker-compose.yml down
